app:
  # 服务器ip，默认使用 0.0.0.0
  host: 127.0.0.1
  # 服务名称
  name: MyBlog
  # 端口号
  port: 7658
setting:
  # jwt密钥
  jwtSecret: BearBo666.
  # jwt过期时间
  jwtTimeout: 4320 # 24* 180 小时
development:
  # 数据库类型 mysql，sqlite3， postgres
  driver: mysql
  # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  source: root:XiongBo2001.@tcp(127.0.0.1:3306)/learning?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
